import type { DemographicScenario } from '../../types';

export const DEMOGRAPHIC_PRESETS: DemographicScenario[] = [
  {
    id: 'average-filipino-woman',
    name: 'Average Filipino Woman',
    targetGroup: 'General Adult Female Cohort',
    description: 'Baseline physiological and exposure parameters for adult women in the Philippines based on national dietary and health surveys.',
    parameters: {
      dailyIntake: {
        id: 'dailyIntake',
        name: 'Daily PFAS Intake',
        unit: 'µg/day',
        description: 'Estimated total daily dietary & water ingestion of PFAS.',
        scientificContext: 'Combines drinking water and seafood ingestion estimates.',
        distribution: { type: 'lognormal', mean: 0.05, sd: 0.02 },
      },
      bodyWeight: {
        id: 'bodyWeight',
        name: 'Body Weight',
        unit: 'kg',
        description: 'Adult female body mass.',
        scientificContext: 'Philippine National Nutrition Council survey baseline mean of 55.4 kg.',
        distribution: { type: 'normal', mean: 55.4, sd: 8.2 },
      },
      age: {
        id: 'age',
        name: 'Age',
        unit: 'years',
        description: 'Age range of exposed demographic cohort.',
        scientificContext: 'Reproductive age span.',
        distribution: { type: 'uniform', min: 18, max: 45 },
      },
      waterConsumption: {
        id: 'waterConsumption',
        name: 'Daily Drinking Water',
        unit: 'L/day',
        description: 'Daily direct drinking water intake.',
        scientificContext: 'Tropical hydration needs average 2.0 L/day.',
        distribution: { type: 'triangular', min: 1.2, mode: 2.0, max: 3.5 },
      },
      bioavailability: {
        id: 'bioavailability',
        name: 'Gastrointestinal Bioavailability',
        unit: 'fraction',
        description: 'Fraction of ingested PFAS absorbed into systemic blood circulation.',
        scientificContext: 'PFAS compounds like PFOA exhibit near-complete absorption (>90%).',
        distribution: { type: 'uniform', min: 0.85, max: 0.99 },
      },
      eliminationHalfLife: {
        id: 'eliminationHalfLife',
        name: 'Elimination Half-Life',
        unit: 'years',
        description: 'Biological excretion half-life in human blood serum.',
        scientificContext: 'PFOA half-life in humans averages 2.7 to 3.8 years.',
        distribution: { type: 'lognormal', mean: 3.2, sd: 0.8 },
      },
      exposureDuration: {
        id: 'exposureDuration',
        name: 'Exposure Duration',
        unit: 'years',
        description: 'Cumulative lifespan period of chronic low-dose exposure.',
        scientificContext: 'Assumes long-term residential persistence.',
        distribution: { type: 'uniform', min: 5, max: 30 },
      },
    },
  },
  {
    id: 'pregnant-woman',
    name: 'Pregnant Female Profile',
    targetGroup: 'Maternal Physiology Cohort',
    description: 'Modified volume of distribution and hemodilution adjustments during pregnancy.',
    parameters: {
      dailyIntake: {
        id: 'dailyIntake',
        name: 'Daily PFAS Intake',
        unit: 'µg/day',
        description: 'Maternal dietary & fluid intake.',
        scientificContext: 'Includes prenatal fluid intake recommendations.',
        distribution: { type: 'lognormal', mean: 0.07, sd: 0.03 },
      },
      bodyWeight: {
        id: 'bodyWeight',
        name: 'Body Weight',
        unit: 'kg',
        description: 'Gestational body mass.',
        scientificContext: 'Adjusted for pregnancy weight gain (+10 to 15 kg).',
        distribution: { type: 'normal', mean: 65.2, sd: 9.5 },
      },
      age: {
        id: 'age',
        name: 'Age',
        unit: 'years',
        description: 'Maternal age.',
        scientificContext: 'Reproductive peak years.',
        distribution: { type: 'uniform', min: 20, max: 38 },
      },
      waterConsumption: {
        id: 'waterConsumption',
        name: 'Daily Drinking Water',
        unit: 'L/day',
        description: 'Hydration requirement during pregnancy.',
        scientificContext: 'Increased fluid demands (approx. 2.5-3.0 L).',
        distribution: { type: 'triangular', min: 2.0, mode: 2.8, max: 4.5 },
      },
      bioavailability: {
        id: 'bioavailability',
        name: 'Gastrointestinal Bioavailability',
        unit: 'fraction',
        description: 'GI Absorption rate.',
        scientificContext: 'Unchanged or slightly elevated GI transport.',
        distribution: { type: 'uniform', min: 0.85, max: 0.98 },
      },
      eliminationHalfLife: {
        id: 'eliminationHalfLife',
        name: 'Elimination Half-Life',
        unit: 'years',
        description: 'Apparent serum clearance half-life.',
        scientificContext: 'Placental transfer slightly speeds maternal serum clearance.',
        distribution: { type: 'lognormal', mean: 2.4, sd: 0.6 },
      },
      exposureDuration: {
        id: 'exposureDuration',
        name: 'Exposure Duration',
        unit: 'years',
        description: 'Pre-gestational & gestational exposure history.',
        scientificContext: 'Cumulative exposure prior to term.',
        distribution: { type: 'uniform', min: 5, max: 20 },
      },
    },
  },
];
