import type { DemographicScenario } from '../../types';

export const DEMOGRAPHIC_PRESETS: DemographicScenario[] = [
  {
    id: 'average-filipino-woman',
    name: 'Average Filipino Woman',
    targetGroup: 'General Adult Female Cohort',
    description: 'Baseline physiological and exposure values for adult women in the Philippines, derived from national health and nutrition surveys.',
    parameters: {
      dailyIntake: {
        id: 'dailyIntake',
        name: 'Daily PFAS Intake',
        unit: 'µg/day',
        description: 'Estimated daily ingestion of PFAS from food and drinking water.',
        scientificContext: 'Combines estimates from drinking water and dietary sources.',
        distribution: { type: 'lognormal', mean: 0.05, sd: 0.02 },
      },
      bodyWeight: {
        id: 'bodyWeight',
        name: 'Body Weight',
        unit: 'kg',
        description: 'Adult female body mass.',
        scientificContext: 'Philippine National Nutrition Council survey baseline mean of 55.4 kg.',
        distribution: { type: 'normal', mean: 55.4, sd: 8.2 },
      },
      age: {
        id: 'age',
        name: 'Age',
        unit: 'years',
        description: 'Age range of exposed demographic cohort.',
        scientificContext: 'Reproductive age span.',
        distribution: { type: 'uniform', min: 18, max: 45 },
      },
      waterConsumption: {
        id: 'waterConsumption',
        name: 'Daily Drinking Water',
        unit: 'L/day',
        description: 'Daily direct drinking water intake.',
        scientificContext: 'Tropical hydration needs average 2.0 L/day.',
        distribution: { type: 'triangular', min: 1.2, mode: 2.0, max: 3.5 },
      },
      bioavailability: {
        id: 'bioavailability',
        name: 'Gastrointestinal Bioavailability',
        unit: 'fraction',
        description: 'Fraction of ingested PFAS absorbed into systemic blood circulation.',
        scientificContext: 'PFAS compounds such as PFOA show high oral absorption (>90%).',
        distribution: { type: 'uniform', min: 0.85, max: 0.99 },
      },
      eliminationHalfLife: {
        id: 'eliminationHalfLife',
        name: 'Elimination Half-Life',
        unit: 'years',
        description: 'Biological excretion half-life in human blood serum.',
        scientificContext: 'PFOA half-life in humans averages 2.7 to 3.8 years.',
        distribution: { type: 'lognormal', mean: 3.2, sd: 0.8 },
      },
      exposureDuration: {
        id: 'exposureDuration',
        name: 'Exposure Duration',
        unit: 'years',
        description: 'Cumulative lifespan period of chronic low-dose exposure.',
        scientificContext: 'Assumes sustained residential exposure.',
        distribution: { type: 'uniform', min: 5, max: 30 },
      },
    },
  },
  {
    id: 'pregnant-woman',
    name: 'Pregnant Female Profile',
    targetGroup: 'Maternal Physiology Cohort',
    description: 'Adjusted for plasma volume expansion and maternal physiological changes during pregnancy.',
    parameters: {
      dailyIntake: {
        id: 'dailyIntake',
        name: 'Daily PFAS Intake',
        unit: 'µg/day',
        description: 'Maternal dietary and fluid intake.',
        scientificContext: 'Includes prenatal fluid intake recommendations.',
        distribution: { type: 'lognormal', mean: 0.07, sd: 0.03 },
      },
      bodyWeight: {
        id: 'bodyWeight',
        name: 'Body Weight',
        unit: 'kg',
        description: 'Gestational body mass.',
        scientificContext: 'Adjusted for pregnancy weight gain (+10 to 15 kg).',
        distribution: { type: 'normal', mean: 65.2, sd: 9.5 },
      },
      age: {
        id: 'age',
        name: 'Age',
        unit: 'years',
        description: 'Maternal age.',
        scientificContext: 'Reproductive peak years.',
        distribution: { type: 'uniform', min: 20, max: 38 },
      },
      waterConsumption: {
        id: 'waterConsumption',
        name: 'Daily Drinking Water',
        unit: 'L/day',
        description: 'Hydration requirement during pregnancy.',
        scientificContext: 'Increased fluid demands (approx. 2.5 to 3.0 L).',
        distribution: { type: 'triangular', min: 2.0, mode: 2.8, max: 4.5 },
      },
      bioavailability: {
        id: 'bioavailability',
        name: 'Gastrointestinal Bioavailability',
        unit: 'fraction',
        description: 'GI absorption fraction.',
        scientificContext: 'Unchanged or slightly elevated GI transport.',
        distribution: { type: 'uniform', min: 0.85, max: 0.98 },
      },
      eliminationHalfLife: {
        id: 'eliminationHalfLife',
        name: 'Elimination Half-Life',
        unit: 'years',
        description: 'Apparent serum clearance half-life.',
        scientificContext: 'Transplacental transfer and plasma expansion increase maternal clearance rate.',
        distribution: { type: 'lognormal', mean: 2.4, sd: 0.6 },
      },
      exposureDuration: {
        id: 'exposureDuration',
        name: 'Exposure Duration',
        unit: 'years',
        description: 'Pre-gestational and gestational exposure history.',
        scientificContext: 'Cumulative exposure prior to term.',
        distribution: { type: 'uniform', min: 5, max: 20 },
      },
    },
  },
  {
    id: 'critical-chronic-threshold',
    name: 'Critical Baseline Threshold (25 to 30 yr Chronic)',
    targetGroup: 'Toxicological Benchmark Cohort',
    description: 'Configures a 25 to 30 year exposure period with baseline threshold parameters to evaluate steady-state PFAS body burden and exceedance.',
    parameters: {
      dailyIntake: {
        id: 'dailyIntake',
        name: 'Daily PFAS Intake',
        unit: 'µg/day',
        description: 'Critical daily intake exceeding the toxicological Reference Dose (RfD) threshold.',
        scientificContext: 'Intake at or above the reference dose threshold for a 55.4 kg individual (0.0831 µg/day for PFOA).',
        distribution: { type: 'uniform', min: 0.085, max: 0.12 },
      },
      bodyWeight: {
        id: 'bodyWeight',
        name: 'Body Weight',
        unit: 'kg',
        description: 'Baseline adult female body mass.',
        scientificContext: 'Philippine National Nutrition Council survey baseline mean of 55.4 kg.',
        distribution: { type: 'normal', mean: 55.4, sd: 5.0 },
      },
      age: {
        id: 'age',
        name: 'Age',
        unit: 'years',
        description: 'Adult demographic age range.',
        scientificContext: 'Chronic adult exposure span.',
        distribution: { type: 'uniform', min: 25, max: 55 },
      },
      waterConsumption: {
        id: 'waterConsumption',
        name: 'Daily Drinking Water',
        unit: 'L/day',
        description: 'Direct daily drinking water ingestion.',
        scientificContext: 'Standard adult hydration baseline of 2.0 L/day.',
        distribution: { type: 'triangular', min: 1.5, mode: 2.0, max: 3.0 },
      },
      bioavailability: {
        id: 'bioavailability',
        name: 'Gastrointestinal Bioavailability',
        unit: 'fraction',
        description: 'Gastrointestinal absorption fraction.',
        scientificContext: 'Near-complete absorption typical of perfluorinated carboxylic acids.',
        distribution: { type: 'uniform', min: 0.90, max: 0.98 },
      },
      eliminationHalfLife: {
        id: 'eliminationHalfLife',
        name: 'Elimination Half-Life',
        unit: 'years',
        description: 'Serum retention half-life.',
        scientificContext: 'Baseline PFOA human elimination half-life averaging 3.8 years.',
        distribution: { type: 'normal', mean: 3.8, sd: 0.4 },
      },
      exposureDuration: {
        id: 'exposureDuration',
        name: 'Exposure Duration',
        unit: 'years',
        description: 'Exposure duration reaching over 99% of steady-state capacity.',
        scientificContext: '25 to 30 years corresponds to 6.5 to 8.0 half-lives, reaching steady-state accumulation.',
        distribution: { type: 'uniform', min: 25, max: 30 },
      },
    },
  },
];

